name: âž• New channel request
description: Suggest a new public TV channel
title: "[NEW] "
labels: ["new-channel"]
body:
  - type: input
    id: channel_name
    attributes:
      label: Channel name
      placeholder: e.g. RAI Storia
    validations:
      required: true

  - type: input
    id: stream_url
    attributes:
      label: Stream URL
      description: Public and legal stream URL (M3U8)
      placeholder: https://...
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: Any additional information
